### PR TITLE
Proposing some changes after running myself.

### PR DESCRIPTION
**Pull request by marypublic**
Edited to replace Description with Default.  

Also made it hopefully clearer that ARN is required for SNS Topic but not for Log Group.

Then I fixed a typo I made...

### CODE REVIEW

**Review by dnorth98 — CHANGES_REQUESTED** [review]
Hi @marypublic .  Thanks for the submission.  So, the Description in a CFN template is usually just that - some ad-hoc test to give context to the value expected in a parameter.

The `Default` though is usually an actual value.  So for this case, I wouldn't put the text description in the Default field (since if you didnt' give a value, it would literally use this text), but what we could do is put in a sample ARN.  Likewise for the Log group name, we could use a sample log group name.

ie

```
AlarmNotificationTopicARN:
    Description: ARN of SNS topic to send alerts to
    Default: arn:aws:sns:us-east-1:1234567890:security-alarms
```

and
```
CloudtrailLogGroupName:
    Description: Name of the Cloudtrail log group
    Default: /aws/cloudtrail
```

**Comment by marypublic** [comment]
This was the first time using something like this for me and I did not realize I needed Default at all (until it ran and told me so).  So even just putting both lines in there would help newbies like me.

Thank you.

On Mon, Dec 14, 2020, at 9:37 AM, The Doctor wrote:
> 

> *@dnorth98* requested changes on this pull request.

> Hi @marypublic <https://github.com/marypublic> . Thanks for the submission. So, the Description in a CFN template is usually just that - some ad-hoc test to give context to the value expected in a parameter.

> The `Default` though is usually an actual value. So for this case, I wouldn't put the text description in the Default field (since if you didnt' give a value, it would literally use this text), but what we could do is put in a sample ARN. Likewise for the Log group name, we could use a sample log group name.

> ie

> `AlarmNotificationTopicARN:
    Description: ARN of SNS topic to send alerts to
    Default: arn:aws:sns:us-east-1:1234567890:security-alarms
`
> and

> `CloudtrailLogGroupName:
    Description: Name of the Cloudtrail log group
    Default: /aws/cloudtrail
`

**Comment by dnorth98** [comment]
@marypublic all good!  If you want to my make suggested changes and re-submit the PR, I'll happily merge

**Comment by marypublic** [comment]
Will do.

Thank you.

**Pull request closed without merging**
